### ISSUE TITLE
unspecified times turned into "12:56am"??

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#301] opened 2024-03-12 03:11 UTC
As a band admin, I edited one of our gig info pages ( https://new.gig-o-matic.com/gig/262/ ), and noticed before saving that the call/set/end times were all showing "12:00AM", which seemed reasonable given that this gig's time info is too complex to represent using just 3 fields.
I was surprised to see that after saving, the call/end times were both 12:56AM, and the set time was blank.

**Comment by nocturne-mit** [comment] 2024-03-12 03:18
This happened again just now with https://new.gig-o-matic.com/gig/271/ , where I was absolutely sure the call/set/end times were showing "12:00AM" before I saved it.

**Comment by nocturne-mit** [comment] 2024-03-12 03:33
and again with https://new.gig-o-matic.com/gig/279/

**Comment by aaronoppenheimer** [comment] 2024-03-12 13:20
I can't reproduce this but will keep trying! Probably related to similar issues - #298

**Comment by nocturne-mit** [comment] 2024-03-12 14:02
But, also, I was able to reproduce this just now with a brand new gig created in GO3, https://new.gig-o-matic.com/gig/283/
Steps to reproduce:
1. From Schedule page, click "Add gig"
2. Type a gig name, select a contact, choose start date 3/13/2024, end date 3/14/2024
3. Save gig
4. See call/end times are both 12:56am.

**Comment by aaronoppenheimer** [comment] 2024-03-12 14:07
Ah - it happens for any gig with an end date!

**Comment by loneconspirator** [comment] 2024-03-15 19:31
+1

I'm getting 12:53, and yes, for multi-day gigs with no times specified such as https://new.gig-o-matic.com/gig/329/

**Comment by bklang** [comment] 2024-03-22 21:58
Thanks for the feedback y'all. I'm going to close this in favor of #337 which contains our plans on how to fix this.

**Closed by bklang** 2024-03-22 21:58 UTC
