### ISSUE TITLE
Gcal feed includes cancelled and archived gigs

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#546] opened 2024-09-19 23:00 UTC
The google-calendar feed for my bands includes cancelled and archived gigs, for example:
 https://www.gig-o-matic.com/gig/3340/ (cancelled) 
https://www.gig-o-matic.com/gig/280/ (cancelled and archived)
https://www.gig-o-matic.com/gig/279/ (archived but not cancelled - we replaced this multi-day placeholder with a bunch of per-day events)

The gcal feed would be more usable if it did not include cancelled or archived gigs, or if it did not default to including them.

**Comment by aaronoppenheimer** [comment] 2024-09-21 14:04
Hm - it's true that the band calfeed was serving trashed gigs (fixed in #547) but should not be serving canceled gigs - I can't replicate it.

Archived gigs should be served since they're usually gigs that actually happened and the calfeed is retroactive for a year. If you want to actually delete a gig, it should go in the trash.

**Comment by nocturne-mit** [comment] 2024-09-23 02:29
That’s good to know about the intended function of archived gigs!

It would be great if we can someday figure out why cancelled gigs are showing up, though. My bandmate reported that to me last week and I was immediately able to verify with https://www.gig-o-matic.com/gig/3340/ which is a recently-created 1-day gig that was
subsequently cancelled.

**Comment by aaronoppenheimer** [comment] 2024-09-23 02:35
Hm. If I look at the calendar feed for the band, that gig is not listed. Where are you seeing it?

**Comment by nocturne-mit** [comment] 2024-09-23 11:44
I’m seeing it in my personal gigo calendar feed that includes all my bands. When I originally reported this bug, I was seeing this issue when I subscribed to that personal gigo calendar URL from my personal google calendar account. I added that personal feed URL for the first time to my iOS calendar last night shortly before replying, and did indeed see that gig, as well as the other cancelled-and-archived gig I mentioned, in my iphone’s view of that calendar.

On Sep 22, 2024, at 10:35 PM, aaronoppenheimer ***@***.***> wrote:

﻿

Hm. If I look at the calendar feed for the band, that gig is not listed. Where are you seeing it?

**Comment by aaronoppenheimer** [comment] 2024-09-23 13:05
Aha, I see. It's the personal calfeed, not the "band calfeed" which is public gigs for a single band.

In this case, you're right, it's returning canceled gigs. There is an option to only show gigs with a status of "confirmed" which does filter out canceled gigs, but it also filters out not-canceled but not-yet-confirmed gigs. I'll think about whether it's better to change that to "hide canceled gigs" in which case it'll show confirmed AND non-confirmed gigs, or if there should be another option which hides canceled gigs but leaves the option to show non-confirmed gigs or not. There are probably two different use cases - one for more admin types who want to see everything possibly coming up, and one for rank-and-file members who just want to know what's confirmed. Or maybe not - maybe better to show everything to everyone except cancelled gigs. What do you think?

A

**Comment by aaronoppenheimer** [comment] 2024-09-23 23:55
OK, with some more research, there's already a solution. In your preferences is a checkbox for "hide canceled gigs" - but it's at the very top and easily missed, I think. It's definitely not set in your preferences. If you tick that, the canceled gigs should go away.

I moved it in #548 for better visibility. Maybe it should be checked by default.

**Closed** 2024-10-12 14:07 UTC
